### ISSUE TITLE
UI overhaul needed

### ISSUE THREAD

**Issue by SeadomGames** [Abc6782/Abc6782.github.io#1]
Things that need to be addressed:
 

- [x] Dice button does nothing
- [x] Black text on a red background is really hard to read, and the white border around the text doesn't really help. Maybe make all the text white, and for selected pages a lighter blue? Same thing with red text on a red background 
- [x] Retro games page has no images
- [x] Links to each subpage on the headbar

I love the work you're doing, quite a few people from our area use your site on a regular basis. Keep it up!

**Comment by Abc6782** [comment]
all finished

**Comment by SeadomGames** [comment]
Looks great!
