### ISSUE TITLE
Feature request: More idles

### ISSUE THREAD

**Issue by SeadomGames** [Abc6782/Abc6782.github.io#3]
Most of the users of this site are very busy most of the time, and only have a few minutes in each class to check in with it. 

What game type would hit this target audience? 

**Idle games**

I see you've added idle breakout, but that doesn't add much worth to the site because you can get the same game on coolmath with a few ads. A few suggestions on what to add: 

- [ ] Egg inc (added via the same Android module you used to add bitlife)
- [ ] Cookie clicker (iframe to the website maybe)
- [ ] Adventure capitalist

Not completely sure how you would add these because I'm not taking the time to look though your code, but I'm positive it can be done.
Cheers!
-seadom

**Comment by Abc6782** [comment]
I will get to it when I can. Ive been rlly busy

**Comment by Abc6782** [comment]
I've been working on a very extensive update. Let me know what you think of it when I'm finished. Will commit it this weekend.

**Comment by SeadomGames** [comment]
There are certainly more idelers now, this issue is no longer needed.
