### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by 3kh0** [Abc6782/Abc6782.github.io#8]
Hello there!

I have looked through your GitHub repo and I found some things that I believe were taken from my site. I ask that you take them down to respect my work and what I do.
If the original one was blocked then you can contact me and I can give you more links. If you have any questions please feel free to reach out to me!

Thanks!
Echo

**Comment by Animationking11** [comment]
I am 80% sure this project is inactive considering the last update was 8 months ago

**Comment by Animationking11** [comment]
good luck on getting a reply tho

**Comment by nate-games** [comment]
### Hello,
Surprisingly, neither of the contributors have responded. All of these are exact copies of your game assets you compiled. 

RIP 3kh0.net
